# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rsh}
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Pavel Argentov}]
  s.date = %q{2011-09-08}
  s.description = %q{BSD rsh(1) cli program wrapper; pure ruby remote shell client implementation.}
  s.email = %q{argentoff@gmail.com}
  s.extra_rdoc_files = [
    "CHANGELOG.rdoc",
    "LICENSE.rdoc",
    "README.rdoc"
  ]
  s.files = [
    ".autotest",
    ".cvsignore",
    ".document",
    ".rspec",
    ".travis.yml",
    "CHANGELOG.rdoc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.rdoc",
    "README.markdown",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/rsh.rb",
    "rsh.gemspec",
    "spec/rsh_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://argent-smith.github.com/rsh}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{BSD remote shell (RFC-1282) protocol client for ruby}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
  end
end

